pagopa/io-pay-portal

io-functions-pay-portal/.devops/azure-templates/setup-project.yml, io-functions-pay-portal/.devops/code-review-be.yml, io-functions-pay-portal/ActivatePayment/__tests__/handler.test.ts, io-functions-pay-portal/ActivatePayment/handler.ts, io-functions-pay-portal/ActivatePayment/index.ts, io-functions-pay-portal/GetActivationStatus/__tests__/handler.test.ts, io-functions-pay-portal/GetActivationStatus/function.json, io-functions-pay-portal/GetActivationStatus/handler.ts, io-functions-pay-portal/GetActivationStatus/index.ts, io-functions-pay-portal/GetPaymentInfo/__tests__/handler.test.ts, io-functions-pay-portal/GetPaymentInfo/handler.ts, io-functions-pay-portal/GetPaymentInfo/index.ts, io-functions-pay-portal/openapi/index.yaml, io-functions-pay-portal/package.json, io-functions-pay-portal/yarn.lock
The goal of this PR is to add the following API definition (without business logic):
```yaml
"/payment-requests/{rptId}":
x-swagger-router-controller: PagoPAProxyController
parameters:
- name: rptId
in: path
required: true
description: Unique identifier for payments.
type: string
get:
operationId: getPaymentInfo
summary: Get Payment Info
description: Retrieve information about a payment
responses:
"200":
description: Payment information retrieved
schema:
"$ref": "#/definitions/PaymentRequestsGetResponse"
examples:
application/json:
importoSingoloVersamento: 200,
codiceContestoPagamento: "ABC123"
"400":
description: Bad request
schema:
$ref: "#/definitions/ProblemJson"
"401":
description: Bearer token null or expired.
"500":
description: PagoPA services are not available or request is …
```
=> [#175899260] API definition and integration test

io-functions-pay-portal/.devops/azure-templates/setup-project.yml, io-functions-pay-portal/.devops/deploy-function-app.yml, io-functions-pay-portal/ActivatePayment/function.json, io-functions-pay-portal/GetActivationStatus/function.json, io-functions-pay-portal/GetPaymentInfo/function.json, io-functions-pay-portal/host.json, io-functions-pay-portal/package.json
**Description**
This PR adds an azure pipeline to deploy the backend Function App
**Proposed Changes**
- yml file which describes the pipeline
**How Test**
The pipeline contains an health-check stage
=> [#175899260] Azure DevOps Pipeline to publish the backend FunctionApp to deployment slot

io-functions-pay-portal/.devops/deploy-function-app.yml, io-pay-portal-fe/.devops/deploy-pipelines.yml
_Description_
The purpose of this PR is to change from `master` ref declared into pipelines (fe + be) of `io-pay-portal` to `main`
=> [#175844896] fix master to main in to pipelines

io-pay-portal-fe/.devops/deploy-pipelines.yml
fix release_branch from master to main
=> [#175844896] fix release_branch to main

io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
This PR is focused on "fields validation"
- styling of KO/OK message on input fields
- styling of error message
- toggle submit button after KO/OK message
The user must be informed if it hasn't filed accurately the input fields
- linter only
=> [#177037465] Input fields validation

io-functions-pay-portal/PostTransactionsChallenge3ds2/index.ts, io-functions-pay-portal/PostTransactionsMethod3ds2/index.ts, io-functions-pay-portal/env.example, io-functions-pay-portal/utils/page3ds.ts
The PR introduces some fixes for 3ds2 endpoints
1. remove _X-Frame-Options_ header for method endpoint;
2. fix methodPage;
3. fix challenge page to return idTransaction as query parameter.
Run the following script:
- yarn build;
- yarn start.
=> [#176942427] fix endpoints to support 3ds2

io-functions-pay-portal/PostNewslettersRecipients/__tests__/handler.test.ts, io-functions-pay-portal/PostTransactionsMethod3ds2/index.ts, io-functions-pay-portal/env.example, io-functions-pay-portal/utils/config.ts
The PR adds a new env to configure io-pay origin in _PostTransactionMethod3ds2_ api.
=> [IOPAY-86] Added new env var for io-pay origin

io-pay-portal-fe/.devops/deploy-pipelines.yml
=> Rename pipeline variables

io-pay-portal-fe/.devops/deploy-pipelines.yml
=> fix purge cdn

io-pay-portal-fe/.devops/deploy-pipelines.yml
=> Fix resource group name in deploy pipeline

io-pay-portal-fe/src/index.pug
With this PR the unused fields are dropped from the page.
- delete DOM elements
Unused fields aren't useful to the end users
=> [#IOPAY-152] Drop unused fields

io-pay-portal-fe/src/helper.ts, io-pay-portal-fe/src/includes/modalerror.pug, io-pay-portal-fe/src/scss/style.scss
This PR solve several issues tested in UAT
See commit desc
Linter
=> [#IOPAY-101] Several issues

io-functions-pay-portal/clients/pagopa.ts
=> [IOPAY-183] update nodoproxy endpoint

io-pay-portal-fe/src/includes/footer.pug, io-pay-portal-fe/src/includes/modalprivacy.pug, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts, io-pay-portal-fe/src/privacypolicy/index.html
This PR is for create a modal to display the privacy policy
Create a new modal.
Insert text.
Also this project needs a privacy policy.
Linter
=> [#IOPAY-155] aggiungere informativa privacy

io-pay-portal-fe/src/helper.ts
- set origin query param to _payportal_
The goal of this PR is to remove the url in query string and pass _payportal_ to decide the final redirect.
=> [IOPAY-210] update origin param

io-pay-portal-fe/src/helper.ts, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
This PR improve UX when user copy/paste the "codice avviso" code and "codice fiscale ente".
I've change the event listner using "input" instead of "keyup"
In this way the user can paste strings
Linter
=> [#IOPAY-186] come cit voglio poter incollare il codice avviso

io-pay-portal-fe/src/helper.ts, io-pay-portal-fe/src/index.ts
With this PR we show in error-modal a Title plus a body text
Created a new _enum_ to map also "body message" for error-modal
Better UX with title + text
Linter
=> [#IOPAY-181] migliorare i testi di errore

io-pay-portal-fe/src/util/mixpanelHelperInit.ts
- Disabled _mixpanel_ cookie in order to avoid a _Domain part overly broad_;
- Enabled _mixpanel_ to use _localStorage_;
=> [IOPAY-218] mixpanel - Switch from Cookies to localStorage

io-pay-portal-fe/src/index.pug
- Deleted _Content Security Policy_ defined in html;
The goal is to move the _Content Security Policy_ from html to headers, thanks to the [rewrite rules](https://github.com/pagopa/io-infrastructure-live-new/blob/5a4441bf1f068d1ea40a8b485fe962f331eaaf84/prod/westeurope/common/cdn/cdn_endpoint_iopayportal/terragrunt.hcl#L48) that can be defined on the _Azure Endpoint_.
=> [IOPAY-220] Deleted csp in html

io-pay-portal-fe/src/index.pug
=> [#IOPAY-229] Added class btn-sm

io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/scss/style.scss
This PR add text about Google privacy policy and hide the google badge.
Added text.
Modified badge css class.
We need to inform user about the use of Google Recaptcha service
Linter
=> [#IOPAY-239] Added google privacy pol.

io-functions-pay-portal/GetPaymentInfo/__tests__/handler.test.ts, io-functions-pay-portal/clients/pagopa.ts, io-functions-pay-portal/openapi/index.yaml, io-functions-pay-portal/package.json, io-functions-pay-portal/utils/pagopaProxyUtil.ts, io-functions-pay-portal/utils/tests/pagopaProxyUtil.test.ts, io-pay-portal-fe/dev-server.js, io-pay-portal-fe/src/helper.ts, io-pay-portal-fe/src/includes/modalerror.pug, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts, io-pay-portal-fe/src/scss/style.scss, io-pay-portal-fe/src/util/errors-def.ts, io-pay-portal-fe/src/util/errors.ts
This PR maps the errors returned by the "proxy" and the style specifically designed.
- modified the mock to obtain different example of "returns"
- modified the css of the modal-error
- mapped all the errors with the custom text to show
- re-arranged the files to improve the readability 
This PR is needed to show the new/correct error returned by the "proxy"
- review
- linter
=> [#IOPAY-260] errorcode

io-pay-portal-fe/src/scss/style.scss
This PR style the buttons as sticky when in mobile, static when in desktop.
=> [#276] Style the buttons: sticky only on mobile

io-pay-portal-fe/src/includes/modal.pug, io-pay-portal-fe/src/index.ts, io-pay-portal-fe/src/scss/style.scss
This PR render the "preview of Avviso di pagamento" with a proportional height
=> [#IOPAY-275] Preview modal without scroll

io-functions-pay-portal/clients/pagopa.ts
=> set prod env

io-pay-portal-fe/src/includes/modal.pug, io-pay-portal-fe/src/includes/modalerror.pug, io-pay-portal-fe/src/includes/modalprivacy.pug, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts, io-pay-portal-fe/src/util/errors.ts
This PR enhance accessibility
- New attributes for html nodes
- focus change strategy in js
This PR enhance accessibility
- Linter
- tsc
=> [#IOPAY-254] accessibility

io-pay-portal-fe/src/index.pug
This PR fixes the font size of the initial disclaimer (as per design), and a typo (missing 'o' in 'servizio').
See above
Not tested
=> [IOPAY-299] Update index.pug

io-pay-portal-fe/.devops/pagopa-deploy-pipelines.yml
=> fix pipeline

io-pay-portal-fe/src/includes/footer.pug
Accessibility statement url in footer
=> [#IOPAY-254] Accessibility statement url

io-pay-portal-fe/dev-server.js, io-pay-portal-fe/src/util/errors-def.ts
- Add PPT_PAGAMENTO_DUPLICATO in error definitions
- Add PPT_PAGAMENTO_IN_CORSO in error definitions
- Update dev-server api endpoint
- Add dev-server mocked response 
- Display specific modal for new cases
Local machine: dev-server
=> [IOPAY-342] Add support for new error response message details

io-pay-portal-fe/src/util/mixpanelHelperInit.ts
=> [IOPAY] delete referrer mixpanel

io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
- fix invisible recaptcha according to thi docs https://developers.google.com/recaptcha/docs/invisible
=> fix invisible recaptcha

io-pay-portal-fe/dev-server.js, io-pay-portal-fe/package.json, io-pay-portal-fe/src/includes/onetrust-dev.html, io-pay-portal-fe/src/includes/onetrust.html, io-pay-portal-fe/src/index.ts, io-pay-portal-fe/src/privacy.pug, io-pay-portal-fe/src/privacypolicy/index.html
OT cookie consent must be "validate" until fire mixpanel init event.
- Added ready prod script from OT
- create a global funct to init Mixpanel
GDPR rules
=> [#IOPAY-358] OT integration with explicit consent event

io-pay-portal-fe/.devops/pagopa-deploy-pipelines.yml, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
This PR put oneTrust func callback in our script
- added callback
=> Onetrust callback

io-pay-portal-fe/src/index.ts
FIX: when a user clicks the "back button" the first screen is loaded instead the navigation flow
=> [#IOPAY-363] Manage navigation between screens

io-pay-portal-fe/src/index.ts
FIX : scroll to top when user "change" the screen (first to second, and vice versa)
- added scrollTop to document
FIX : scroll to top when user "change" the screen (first to second, and vice versa)
=> [#IOPAY-375] Scroll to top 

io-pay-portal-fe/package.json, io-pay-portal-fe/robots.txt
- add `robots.txt`
- update build script, in order to copy `robots.txt` in dist folder
=> Iopay 359 robots txt

io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
This PR modifies the organizationId UX changing validation & response message.
Now this field requires only 11 numbers, no more chars.
- modified regexp
- modified response message
The organizationId field requires only 11 numbers, no more chars.
=> [#IOPAY-384] verificare campo massimo ec

io-pay-portal-fe/package.json
- update openapi spec to generate _checkout API client._
=> update spec with new checkout function

io-pay-portal-fe/src/privacypolicy/index.html
Update privacy text as asked by Legal
=> [#IOPAY-428] Update privacy text

io-pay-portal-fe/dev-server.js, io-pay-portal-fe/src/util/errors-def.ts
This PR add a new error code : PPT_ERRORE_EMESSO_DA_PAA
- Added PPT_ERRORE_EMESSO_DA_PAA to the errors dictionary
- Added PPT_ERRORE_EMESSO_DA_PAA to dev mock
A more specific description of this error is needed to help users
- Lint
=> [#IOPAY-424] Added err code PPT_ERRORE_EMESSO_DA_PAA

io-pay-portal-fe/.devops/azure-templates/make-build.yml, io-pay-portal-fe/.devops/pagopa-deploy-pipelines.yml
- refactoring in order to handle configuration in pipeline azure yml
- update configuration for payment activations polling
=> [HOTFIX] increase interval and attempts - polling activations

io-pay-portal-fe/dev-proxy-server.js
* Add integration with `pagopa-checkout-backend-mock`
=> Add integration with `pagopa-checkout-backend-mock`

io-pay-portal-fe/REMOVE_THIS_api/openapi.yml, io-pay-portal-fe/package.json, io-pay-portal-fe/src/helper.ts, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/index.ts
**READ BEFORE APPROVING**
This is intended as a draft pull request and only useful in evaluating the approach of requiring a double captcha is valid.
In order to properly land the PR integration with the backend is needed (and subsequent updating of the swagger URL in `package.json`, this branch uses a modified local copy)
Depends on pagopa/pagopa-infra#170
* Add recaptcha to activation phase
This change makes interacting with the associated backend endpoint more secure
Local manual testing
=> Add recaptcha to activation phase

io-pay-portal-fe/.devops/azure-templates/make-build.yml, io-pay-portal-fe/.devops/pagopa-deploy-pipelines.yml
Add new timeout_polling_alert param in pipeline in order to handle https://github.com/pagopa/io-pay-portal/pull/136
=> Add new timeout_polling_alert param in pipeline

io-pay-portal-fe/.devops/pagopa-deploy-pipelines.yml
=> Update donations url

io-pay-portal-fe/src/dona.pug, io-pay-portal-fe/src/scss/style.scss
- Copy fixes
- Disabled state style fix
- Changes to match with design
-
=> [IOPAY-535] Minor fixes

io-pay-portal-fe/src/dona.pug
New page title for Donations
- [x ] New feature (non-breaking change which adds functionality)
=> [IOPAY-555] Update page title

io-pay-portal-fe/src/dona.pug, io-pay-portal-fe/src/includes/modalqrcode.pug, io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/scss/style.scss
=> [IOPAY-557] Cosmetic fixes

io-pay-portal-fe/src/dona.pug, io-pay-portal-fe/src/dona.ts
The goal of this PR is to manage the button "Dona con app IO" as a link when on mobile viewport.
- added js to manage the button "dona con app IO" as a link
=> [#IOPAY-558]  "Dona con app IO" on mobile

io-pay-portal-fe/src/dona.pug
=> [IOPAY-567] Update dona.pug

io-pay-portal-fe/src/dona.pug, io-pay-portal-fe/src/includes/head.pug
The goal is to obtain a specific twitter thumb for dona.html
- Parametric img for twitter thumb image
=> [#IOPAY-569] Twitter thumb for Dona

io-pay-portal-fe/src/dona.pug
This PR is useful to modify Privacy button text (according with Legalz) and create a specific link to read the full text
- Modified link text & href
=> [#IOPAY-576] Add privacy link

io-pay-portal-fe/src/dona.pug
HOTFIX: add full width to the state card
=> [#IOPAY-593] miss width

io-pay-portal-fe/src/dona.ts
This PR fixes the ordering flow of organizations in "dona" page.
- added sorting function in dona.ts
We need to order by name
=> [#IOPAY-595] Ordering org by name

io-pay-portal-fe/src/index.pug, io-pay-portal-fe/src/scss/style.scss
This PR set a temporary banner in the home to display a warning message
=> [#IOPAY-632] Set temp banner

io-functions-pay-portal/PostNewslettersRecipients/__tests__/handler.test.ts, io-functions-pay-portal/PostNewslettersRecipients/handler.ts, io-functions-pay-portal/openapi/index.yaml
- add `organization` and `surname` as optional field in newsletter API.
The goal of this PR is to add new optional field  in newsletter API, to use in  Field of mailup API:
```             
Fields: [
{
Description: "campo1",
Value: name
},
{
Description: "campo2",
Value: surname
},
{
Description: "campo3",
Value: organization
}
]
```
according to mailup docs https://help.mailup.com/display/mailupapi/Recipients.
=> feat: add organization optional field newsletters
